---
# Check for IOMMU and set it (https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Deployment_and_Administration_Guide/chap-Guest_virtual_machine_device_configuration.html#sect-Guest_virtual_machine_device_configuration-PCI_devices)
# Intel VT-x or AMD SVM?
# grep vmx /proc/cpuinfo
# grep svm /proc/cpuinfo

- name: enable PCI passthrough
  lineinfile:
    dest: /etc/sysconfig/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*intel_iommu)\"[^\"]+)(\".*)'
    line: '\1 intel_iommu=pt\2'
    backrefs: yes
  when: enable_pci_passthrough | default(false)

# amd_iommu=pt

- name: configure Wok server
  template: 
    src: wok.conf.j2
    dest: /etc/wok/wok.conf
    force: yes
    backup: yes
  when: wok is defined
  notify: restart wokd

- name: configure nginx for Wok server
  template:
    src: nginx_nossl_wok.conf.j2
    dest: /etc/nginx/conf.d/wok.conf
    force: yes
    backup: yes
  when: wok.nginx_ssl_disable == true
  notify: restart nginx

- name: configure nginx for Wok server
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes
    backup: yes
  notify: restart nginx

- name: configure nginx for Wok server
  template:
    src: nginx_nossl_wok.conf.j2
    dest: /etc/nginx/conf.d/wok.conf
    force: yes
    backup: yes
  when: (wok.https_redirect == true) and (wok.nginx_ssl_disable == false)
  notify: restart nginx

- name: configure nginx for Wok server
  template:
    src: nginx_nossl_wok.conf.j2
    dest: /etc/nginx/conf.d/wok.conf
    force: yes
    backup: yes
  when: (wok.https_redirect == false) and (wok.nginx_ssl_disable == false)
  notify: restart nginx
