---
- name: install Kimchi and its prerequisites Wok and Ginger-base
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
  - https://kimchi-project.github.io/wok/downloads/latest/wok.el7.centos.noarch.rpm
  - https://kimchi-project.github.io/gingerbase/downloads/latest/ginger-base.el7.centos.noarch.rpm
  - https://kimchi-project.github.io/kimchi/downloads/latest/kimchi.el7.centos.noarch.rpm
