---
- name: open ports for wokd
  firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
  - "{{ wok.port | default(8000) }}/tcp"
  - "{{ wok.ssl_port | default(8001) }}/tcp"

- name: provide fixed systemd unit file
  template:
    src: wokd.service.j2
    dest: "/etc/systemd/system/wokd.service"
    owner: root
    group: root
    mode: 0644

- name: allow nginx to bind to necessary ports
  seport:
    ports: "{{ wok.port | default(8000) }},{{ wok.ssl_port | default(8001) }},{{ wok.cherrypy_port | default(8010) }},{{ wok.websockets_port | default(64667) }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: start and enable wokd
  systemd:
    name: wokd
    daemon_reload: yes
    enabled: yes
    state: started
