---
- name: open ports for wokd
  firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
  - "{{ wok.port | default(8000) }}/tcp"
  - "{{ wok.ssl_port | default(8001) }}/tcp"

- name: provide fixed systemd unit file
  template:
    src: wokd.service.j2
    dest: "/etc/systemd/system/wokd.service"
    owner: root
    group: root
    mode: 0644

- name: start and enable wokd
  systemd:
    name: wokd
    daemon_reload: yes
    enabled: yes
    state: started

- name: start and enable nginx
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started
