---
- name: open port for wokd
  firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    port: 8000-8001/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: start wokd
  systemd:
    name: wokd
    enabled: yes
    state: started

