---
- name: open port for wokd
  firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    port: 8000-8001/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: provide fixed systemd unit file
  template:
    src: wokd.service.j2
    dest: "/etc/systemd/system/wokd.service"
    owner: root
    group: root
    mode: 0644

- name: allow nginx to bind to necessary ports
  seport:
    ports: 8000-8001,8010,64667
    proto: tcp
    setype: http_port_t
    state: present

- name: start and enable wokd
  systemd:
    name: wokd
    daemon_reload: yes
    enabled: yes
    state: started
