---
- name: add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    enabled: no
    gpgkey: https://getfedora.org/static/352C64E5.txt
